### ISSUE TITLE
Script fails to bootstrap with node 7.1.0 and yarn 0.17.10

### ISSUE THREAD

**Issue by marccampbell** [auth0-community/auth0-react-scripts#2]
### Description

Installation fails with the message ```error Couldn't find a package.json file in "[snip]/my-app/node_modules/auth0-react-scripts/node_modules/babel-preset-react-app"```

### Actual behavior

The full output of running the command is:

```bash
$ create-react-app my-app --scripts-version auth0-react-scripts
Creating a new React app in /git/my-app.

Installing packages. This might take a couple minutes.
Installing react-scripts...

yarn add v0.17.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning auth0-react-scripts > jest > jest-cli > istanbul-api > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "babel-eslint@6.1.2".
warning Unmet peer dependency "eslint@3.5.0".
warning Unmet peer dependency "eslint-plugin-flowtype@2.18.1".
warning Unmet peer dependency "eslint-plugin-import@1.12.0".
warning Unmet peer dependency "eslint-plugin-jsx-a11y@2.2.2".
warning Unmet peer dependency "eslint-plugin-react@6.3.0".
warning Unmet peer dependency "eslint@>=1.6.0 <4.0.0".
warning Unmet peer dependency "eslint@2.x - 3.x".
warning Unmet peer dependency "eslint@^2.10.2 || 3.x".
warning Unmet peer dependency "webpack@^1.9.11".
warning Unmet peer dependency "babel-core@^6.0.0".
warning Unmet peer dependency "webpack@1 || ^2.1.0-beta".
warning Unmet peer dependency "eslint@^2.0.0 || ^3.0.0".
warning Unmet peer dependency "webpack@*".
warning Unmet peer dependency "eslint@>=2.0.0".
warning Unmet peer dependency "webpack@^1.13.2".
warning Unmet peer dependency "file-loader@*".
warning Unmet peer dependency "webpack@>=1.3.0 <3".
warning Unmet peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
error Couldn't find a package.json file in "/git/my-app/node_modules/auth0-react-scripts/node_modules/babel-preset-react-app"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn add --dev --exact auth0-react-scripts failed
```

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls react-scripts` (if you haven’t ejected): 
2. `node -v`: v7.1.0
3. `npm -v`: 4.0.3

Then, specify:

1. Operating system: macOS 10.12

**Comment by Laurian** [comment]
uninstalling yarn worked for me

**Comment by unicodeveloper** [comment]
Yes, @marccampbell please go ahead and install yarn temporarily. There is currently a bug with Yarn that stops execution of the `auth0-react-scripts` due to missing package.json files.

Actually, the `package.json` file exists but Yarn seems not to find them for some unexplainable reasons. 

Uninstalling Yarn will allow `create-react-app` invoke `npm` to do the installation, which will totally work fine.

**Comment by Robdel12** [comment]
Is there a related yarn issue for this?

**Comment by hchoriq** [comment]
Node 7 doesn't work for me. Once I used Node 6 in nvm (and npm 3), npm start would finally work. I'm getting something else now: Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`. but that's a different issue.
