### ISSUE TITLE
auth0-lock-passwordless support

### ISSUE THREAD

**Issue by Laurian** [auth0-community/auth0-react-scripts#3]
It would be helpful to have an example with `auth0-lock-passwordless`

**Comment by darkyen** [comment]
Auth0 Lock 10.10.2 adds support for Passwordless Auth :D

**Comment by vipulbhj** [comment]
auth0-lock-passwordless has been deprecated right???
Is this still open for implementation ??

**Comment by beardaway** [comment]
That is correct. It has been deprecated.
