### ISSUE TITLE
proposal not to fork react-scripts for example app

### ISSUE THREAD

**Issue by bebbi** [auth0-community/auth0-react-scripts#6]
I'm not sure what's the scope of this code and why it's forked from react-script.

If it's just an example, I would propose to just publish a /src directory and whatever else is needed - then it's more transparent what's the actual diff to a regular CRA.

If it's meant as a scaffold, it's awkward by design to stay on top of CRAs react-script and a custom fork that's already a bit outdated, and then wait until bugfixes trickle through. For example, CRA with this react-script fork fails to even install if `yarn` package manager is installed globally. (`npm i -g yarn`).

**Comment by beardaway** [comment]
Hey there @bebbi ! Sorry for such delay in response. Totally agree in terms of what you've written. We're currently under development of our new OSS ecosystem of GitHub repos to provide you folks with more consistent, regular and above all better experience. Will definitely take it into account when redesigning the repo.

Thanks for help and one more time sorry for the inconvenience! 🙏🏼
